### ISSUE TITLE
Instalaltion Page

### ISSUE THREAD

**Issue by spartaelcid** [advocaite/Travianx#105]
Hello,

i clone this project, and run the server but i don't found the instalaltion page guide :/

How can found it ?

Regards

**Comment by spartaelcid** [comment]
Hello,

when i'm at step 3 (databases) i have this error:

[Sun Nov  4 18:15:38 2018] 188.218.12.201:52799 [500]: /install/process.php - Uncaught Error: Call to undefined function mysql_connect() in /root/Travianx/install/include/database.php:30
Stack trace:
#0 /root/Travianx/install/include/database.php(60): MYSQL_DB->MYSQL_DB()
#1 /root/Travianx/install/process.php(13): include('/root/Travianx/...')
#2 {main}
  thrown in /root/Travianx/install/include/database.php on line 30

**Comment by eyquincho** [comment]
> Hello,
> 
> when i'm at step 3 (databases) i have this error:
> 
> [Sun Nov 4 18:15:38 2018] 188.218.12.201:52799 [500]: /install/process.php - Uncaught Error: Call to undefined function mysql_connect() in /root/Travianx/install/include/database.php:30
> Stack trace:
> #0 /root/Travianx/install/include/database.php(60): MYSQL_DB->MYSQL_DB()
> #1 /root/Travianx/install/process.php(13): include('/root/Travianx/...')
> #2 {main}
> thrown in /root/Travianx/install/include/database.php on line 30

It seems like the whole thing isn't ready for PHP 5.5+
